### ISSUE TITLE
建议将SetRollingFile与SetRollingDaily合并或提供一个合并函数

### ISSUE THREAD

**Issue by maxid** [donnie4w/go-logger#3]
建议将SetRollingFile与SetRollingDaily合并，或提供一个合并函数
Recommended to SetRollingFile with SetRollingDaily merge, or to provide a merge function

**Comment by Bruce-sz** [comment]
请问这个项目有在实际项目用过吗？

**Comment by donnie4w** [comment]
一直在使用

Bruce-sz <notifications@github.com>编写：

**Comment by Bruce-sz** [comment]
@donnie4w 
好的，谢谢〜
