### ISSUE TITLE
啊呀，设计是可以的 ，就是好多bug，issue也不处理

### ISSUE THREAD

**Issue by HKMV** [donnie4w/go-logger#30]
有时间自己魔改一波

**Comment by donnie4w** [comment]
issue中大部分bug已经修改了，可能有漏改或没发现的bug，发现麻烦提一下吧，谢谢
donnie
***@***.***
---- 回复的原邮件 ----
***@***.***>发送日期2024年5月11日 ***@***.***>***@***.***>主题[donnie4w/go-logger] 啊呀，设计是可以的 ，就是好多bug，issue也不处理 (Issue #30)
有时间自己魔改一波

**Comment by donnie4w** [comment]
@HKMV  通常测试，并未发现bug，若有发现，请提一下issue

**Comment by HKMV** [comment]
比如，
1.你自己写的工具依赖这个项目的mod中没有更新，导致使用时编译失败
2.配置了分片保存的文件名不生效，日志还是输出到了你默认的文件名文件中
3.日志第一个参数不支持format

**Comment by algocrafter** [comment]
你好 Serenity：
对于你提出的第一与第三个问题，我理解它们似乎并不属于bug，所以我这里暂不处理。
对于第二个问题，我比较重视，但是还不太理解问题具体情况。你是否可以提供比较具体使用过程。
对于logger的文件设置，我知道的是，它只能被设置一次（一般在logger对象创建的时候设定），
若涉及到文件需要重新指定，那么需要重新创建日志对象，并设定最新文件路径。
而如果旧的日志文件不再需要写入数据时，可以关闭相应日志对象，调用对象的SetLevel(logger.LEVEL_OFF)函数










---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年5月14日 18:08 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | Re: [donnie4w/go-logger] 啊呀，设计是可以的 ，就是好多bug，issue也不处理 (Issue #30) |

比如，
1.你自己写的工具依赖这个项目的mod中没有更新，导致使用时编译失败
2.配置了分片保存的文件名不生效，日志还是输出到了你默认的文件名文件中
3.日志第一个参数不支持format

**Comment by donnie4w** [comment]
@HKMV 
你好 Serenity：
对于你提出的第一与第三个问题，我理解它们似乎并不属于bug，所以我这里暂不处理。
对于第二个问题，我比较重视，但是还不太理解问题具体情况。你是否可以提供比较具体使用过程。
对于logger的文件设置，我知道的是，它只能被设置一次（一般在logger对象创建的时候设定），
若涉及到文件需要重新指定，那么需要重新创建日志对象，并设定最新文件路径。
而如果旧的日志文件不再需要写入数据时，可以关闭相应日志对象，调用对象的SetLevel(logger.LEVEL_OFF)函数

**Comment by HKMV** [comment]
> @HKMV 
> 你好 Serenity：
> 对于你提出的第一与第三个问题，我理解它们似乎并不属于bug，所以我这里暂不处理。
> 对于第二个问题，我比较重视，但是还不太理解问题具体情况。你是否可以提供比较具体使用过程。
> 对于logger的文件设置，我知道的是，它只能被设置一次（一般在logger对象创建的时候设定），
> 若涉及到文件需要重新指定，那么需要重新创建日志对象，并设定最新文件路径。
> 而如果旧的日志文件不再需要写入数据时，可以关闭相应日志对象，调用对象的SetLevel(logger.LEVEL_OFF)函数

对于第一个问题由于使用依赖导致无法编译，这怎么能不算bug呢，更新一下依赖就能解决的事情😀
对于第二个问题，明天到公司我把我的用法发出来你看下。

**Comment by HKMV** [comment]
> @HKMV 你好 Serenity： 对于你提出的第一与第三个问题，我理解它们似乎并不属于bug，所以我这里暂不处理。 对于第二个问题，我比较重视，但是还不太理解问题具体情况。你是否可以提供比较具体使用过程。 对于logger的文件设置，我知道的是，它只能被设置一次（一般在logger对象创建的时候设定）， 若涉及到文件需要重新指定，那么需要重新创建日志对象，并设定最新文件路径。 而如果旧的日志文件不再需要写入数据时，可以关闭相应日志对象，调用对象的SetLevel(logger.LEVEL_OFF)函数

找到原因了：你这里设计的SetRollingDaily和SetRollingFile不可以共用；其实在实际业务中很有必要公用，因为每天的日志有可能会很大，不太方便查看；你可能会说可以采用小时分割方案，但是这样就会产生很多小的日志文件，因为业务往往集中在某个时间段。

**Comment by donnie4w** [comment]
好的，谢谢！你的提议很重要，我会在接下来的程序优化或重构的时候，充分考虑你的意见。
donnie
***@***.***
---- 回复的原邮件 ----
***@***.***>发送日期2024年5月16日 ***@***.***>***@***.***>,
State ***@***.***>主题Re: [donnie4w/go-logger] 啊呀，设计是可以的 ，就是好多bug，issue也不处理 (Issue #30)
@HKMV 你好 Serenity： 对于你提出的第一与第三个问题，我理解它们似乎并不属于bug，所以我这里暂不处理。 对于第二个问题，我比较重视，但是还不太理解问题具体情况。你是否可以提供比较具体使用过程。 对于logger的文件设置，我知道的是，它只能被设置一次（一般在logger对象创建的时候设定）， 若涉及到文件需要重新指定，那么需要重新创建日志对象，并设定最新文件路径。 而如果旧的日志文件不再需要写入数据时，可以关闭相应日志对象，调用对象的SetLevel(logger.LEVEL_OFF)函数
找到原因了：你这里设计的SetRollingDaily和SetRollingFile不可以共用；其实在实际业务中很有必要公用，因为每天的日志有可能会很大，不太方便查看；你可能会说可以采用小时分割方案，但是这样就会产生很多小的日志文件，因为业务往往集中在某个时间段。

**Comment by HKMV** [comment]
> 好的，谢谢！你的提议很重要，我会在接下来的程序优化或重构的时候，充分考虑你的意见。 donnie ***@***.*** ---- 回复的原邮件 ---- ***@***.***>发送日期2024年5月16日 ***@***.***>***@***.***>, State ***@***.***>主题Re: [donnie4w/go-logger] 啊呀，设计是可以的 ，就是好多bug，issue也不处理 (Issue #30) @HKMV 你好 Serenity： 对于你提出的第一与第三个问题，我理解它们似乎并不属于bug，所以我这里暂不处理。 对于第二个问题，我比较重视，但是还不太理解问题具体情况。你是否可以提供比较具体使用过程。 对于logger的文件设置，我知道的是，它只能被设置一次（一般在logger对象创建的时候设定）， 若涉及到文件需要重新指定，那么需要重新创建日志对象，并设定最新文件路径。 而如果旧的日志文件不再需要写入数据时，可以关闭相应日志对象，调用对象的SetLevel(logger.LEVEL_OFF)函数 找到原因了：你这里设计的SetRollingDaily和SetRollingFile不可以共用；其实在实际业务中很有必要公用，因为每天的日志有可能会很大，不太方便查看；你可能会说可以采用小时分割方案，但是这样就会产生很多小的日志文件，因为业务往往集中在某个时间段。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***>

如果你乐意，我可以协助一块维护。
