### ISSUE TITLE
slog按天切割日志不是按时切割

### ISSUE THREAD

**Issue by vinsonzou** [donnie4w/go-logger#31]
比如写入a.log，跨天后有日志才会切割，没有日志永远也不会切割。

比如6月1日的日志a.log，下次输出日志为5号，则切割日志为4号了，与实际不符。

**Comment by donnie4w** [comment]
是的，目前程序写的逻辑应该是结果。
如果按天备份，出现某天没有日志的情况，会有这些你说的情况。

这个可以优化一下，我会发一个小版本 v0.25.1，优化这个问题，包括按时，天，月份。

**Comment by vinsonzou** [comment]
更新到v0.25.1后出现了新的问题。
最后一次写入是6月7日，6月8日0点正常切割了。8、9、10日都没正常日志写入，日志保留的还是8日0点切割的日志，大小为0。11日写入第一条日志后，当前日志切割后日期变为11日了。后续11号日志继续写入切割后文件。

**Comment by vinsonzou** [comment]
@donnie4w 服务重启时，切割日志日期变为19700101了
