### ISSUE TITLE
请问是否可以增加配置 支持打印堆栈信息？

### ISSUE THREAD

**Issue by Bronya0** [donnie4w/go-logger#33]
比如在logger.Error()时能携带调用堆栈，zap里可以这么写：logger := zap.New(cores, zap.AddCaller(), zap.AddStacktrace(zap.ErrorLevel))

**Comment by donnie4w** [comment]
@Bronya0 
好的，这个需要增加两个功能点，一个是允许根据不同日志级别定制不同的日志格式或者包含不同的信息，另一个是日志记录点可以回溯到程序入口点的所有函数调用序列，包括每一步函数调用的文件名和行号。
新版本我会尝试实现这些功能。

**Comment by donnie4w** [comment]
@Bronya0 
已发布v0.26.0，增加该功能，具体请查阅[《go-logger v0.26.0》](https://tlnet.top/article/22425211)

**Comment by Bronya0** [comment]
😁

**Comment by Bronya0** [comment]
太牛了
