### ISSUE TITLE
这个日志有什么好办法写多个文件

### ISSUE THREAD

**Issue by waterloopwm** [donnie4w/go-logger#7]
看了例子这样调用
logger.SetConsole(false)
logger.SetLevel(logger.INFO)
logger.SetRollingDaily("./log", "err.log")
但我要把日志写到另外几个文件呢，比如这样
logger.SetRollingDaily("./log", "send.log")
logger.SetRollingDaily("./log", "result.log")
程序跑了一会儿，就报读写锁错误

**Comment by donnie4w** [comment]
具体是什么样的写法？根据level不同级别写到不同文件？还是什么规则写到指定文件？

**Comment by waterloopwm** [comment]
logger.SetConsole(false)
logger.SetLevel(logger.INFO)
级别都相同，但要写几个日志文件

某个函数里面这样设置
logger.SetRollingDaily("./log", "err.log")
某个函数里面这样设置logger.SetRollingDaily("./log", "send.log")
某个函数里面这样设置logger.SetRollingDaily("./log", "result.log")
开始写日志文件，就报读写锁错误

**Comment by donnie4w** [comment]
是的。
现在logger里面操作对象是全局对象，你那样设置会有问题。
我上面的问题没表述清楚， 我的意思是你想要的效果是什么样的？
这个写的比较早，我也准备升级优化一下这个logger工具

**Comment by waterloopwm** [comment]
想能写多个日志文件，目前你这个只能写一个日志文件

**Comment by SuperYear** [comment]
现在这个日志是全局的，只能写一个日志文件，但是有时候我们想写多个文件，保存不同的日志，比如一些重要的记录，想永久保存，或者根据不同的业务保存不同业务的错误日志文件。方便查看。
所以希望作者改进一下，能写多个日志文件。

**Comment by waterloopwm** [comment]
作者最近有重写的打算吗

**Comment by donnie4w** [comment]
@waterloopwm  是的，已经在写了
